# Generated by Django 3.2.5 on 2023-04-10 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctset',
            name='build_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 10, 13, 39, 28, 752552)),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 10, 13, 39, 28, 752552)),
        ),
    ]
