# Generated by Django 3.2.5 on 2023-04-10 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230410_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctset',
            name='build_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 42, 6, 937876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 42, 6, 937876, tzinfo=utc)),
        ),
    ]
